server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: climbing
          uri: http://localhost:8082
          predicates:
            - Path=/climbingMemberships/**, /climbingTrainingCourseTickets/**, 
        - id: remine
          uri: http://localhost:8083
          predicates:
            - Path=/membershipRemines/**, /trainingRemines/**, 
        - id: trainingCourse
          uri: http://localhost:8084
          predicates:
            - Path=/climbingTrainingCourseInfos/**, 
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=/climbingNotifications/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: climbing
          uri: http://climbing:8080
          predicates:
            - Path=/climbingMemberships/**, /climbingTrainingCourseTickets/**, 
        - id: remine
          uri: http://remine:8080
          predicates:
            - Path=/membershipRemines/**, /trainingRemines/**, 
        - id: trainingCourse
          uri: http://trainingCourse:8080
          predicates:
            - Path=/climbingTrainingCourseInfos/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/climbingNotifications/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
